version: 2.1

workflows:
  version: 2

  # The build workflow will build a preview for the site, intended for PRs
  build:
    jobs:
      - build-site:
          filters:
            branches:
              ignore: gh-pages


build_jekyll: &build_jekyll
    name: Jekyll Build
    command: |
        echo "Building RSE Blog for Preview"
        cd ~/repo

        # Update baseurl in config
        BASEURL=https://${CIRCLE_BUILD_NUM}-267395254-gh.circle-artifacts.com/0/SORSE20
        sed -i "17 s,.*,baseurl: $BASEURL,g" "_config.yml"
        sed -i "18 s,.*,url: '',g" "_config.yml"

        # Build site to download template
        bundle exec jekyll build

        grep -rlZ '\https' . | xargs -0 sed -i 's:/https:https:g'
        grep -rlZ 'main.css' _site | xargs -0 sed -i "s,.*main.css.*,<link rel=\"stylesheet\" href=\"${BASEURL}/assets/css/main.css\">,g"

 

jobs:
  build-site:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/repo
    environment:
      - JEKYLL_ENV: production
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      - BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies
          - rubygems-v1
      - run:
          name: Bundle Install
          command: |
              cd ~/repo
              bundle check || bundle install
      - save_cache:
          key: rubygems-v1
          paths:
            - vendor/bundle
      - run: *build_jekyll
      - store_artifacts:
          path: ~/repo/_site
          destination: SORSE20
